version: '3'
services:

  virtuoso:
    build:
      context: ./virtuoso
    environment:
      SPARQL_UPDATE: "true"
      DEFAULT_GRAPH: "https://w3id.org/whow"
    volumes:
      - ./virtuoso/graphs:/graphs
      - ./virtuoso/db:/usr/local/virtuoso-opensource/var/lib/virtuoso/db
    ports:
      - "8890:8890"
      - "1111:1111"
  lodview:
    build: ./lodview
    ports:
      - "8181:8080"
    restart: always
